/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationsPeriodApplicationDeveloper {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<i32>,
    #[serde(rename = "apiEulaVersion", skip_serializing_if = "Option::is_none")]
    pub api_eula_version: Option<i32>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::UserPeriodUserInfoCard>>,
}

impl ApplicationsPeriodApplicationDeveloper {
    pub fn new() -> ApplicationsPeriodApplicationDeveloper {
        ApplicationsPeriodApplicationDeveloper {
            role: None,
            api_eula_version: None,
            user: None,
        }
    }
}


