/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationsPeriodApiUsage {
    /// Counts for on API calls made for the time range.
    #[serde(rename = "apiCalls", skip_serializing_if = "Option::is_none")]
    pub api_calls: Option<Vec<crate::models::ApplicationsPeriodSeries>>,
    /// Instances of blocked requests or requests that crossed the warn threshold during the time range.
    #[serde(rename = "throttledRequests", skip_serializing_if = "Option::is_none")]
    pub throttled_requests: Option<Vec<crate::models::ApplicationsPeriodSeries>>,
}

impl ApplicationsPeriodApiUsage {
    pub fn new() -> ApplicationsPeriodApiUsage {
        ApplicationsPeriodApiUsage {
            api_calls: None,
            throttled_requests: None,
        }
    }
}


