/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigPeriodUserTheme {
    #[serde(rename = "userThemeId", skip_serializing_if = "Option::is_none")]
    pub user_theme_id: Option<i32>,
    #[serde(rename = "userThemeName", skip_serializing_if = "Option::is_none")]
    pub user_theme_name: Option<String>,
    #[serde(rename = "userThemeDescription", skip_serializing_if = "Option::is_none")]
    pub user_theme_description: Option<String>,
}

impl ConfigPeriodUserTheme {
    pub fn new() -> ConfigPeriodUserTheme {
        ConfigPeriodUserTheme {
            user_theme_id: None,
            user_theme_name: None,
            user_theme_description: None,
        }
    }
}


