/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentPeriodNewsArticleRssItem {
    #[serde(rename = "Title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "Link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "PubDate", skip_serializing_if = "Option::is_none")]
    pub pub_date: Option<String>,
    #[serde(rename = "UniqueIdentifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ContentPeriodNewsArticleRssItem {
    pub fn new() -> ContentPeriodNewsArticleRssItem {
        ContentPeriodNewsArticleRssItem {
            title: None,
            link: None,
            pub_date: None,
            unique_identifier: None,
            description: None,
        }
    }
}


