/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentPeriodModelsPeriodContentTypeDefaultValue {
    #[serde(rename = "whenClause", skip_serializing_if = "Option::is_none")]
    pub when_clause: Option<String>,
    #[serde(rename = "whenValue", skip_serializing_if = "Option::is_none")]
    pub when_value: Option<String>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
}

impl ContentPeriodModelsPeriodContentTypeDefaultValue {
    pub fn new() -> ContentPeriodModelsPeriodContentTypeDefaultValue {
        ContentPeriodModelsPeriodContentTypeDefaultValue {
            when_clause: None,
            when_value: None,
            default_value: None,
        }
    }
}


