/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentPeriodNewsArticleRssResponse {
    #[serde(rename = "NewsArticles", skip_serializing_if = "Option::is_none")]
    pub news_articles: Option<Vec<crate::models::ContentPeriodNewsArticleRssItem>>,
    #[serde(rename = "CurrentPaginationToken", skip_serializing_if = "Option::is_none")]
    pub current_pagination_token: Option<i32>,
    #[serde(rename = "NextPaginationToken", skip_serializing_if = "Option::is_none")]
    pub next_pagination_token: Option<i32>,
    #[serde(rename = "ResultCountThisPage", skip_serializing_if = "Option::is_none")]
    pub result_count_this_page: Option<i32>,
}

impl ContentPeriodNewsArticleRssResponse {
    pub fn new() -> ContentPeriodNewsArticleRssResponse {
        ContentPeriodNewsArticleRssResponse {
            news_articles: None,
            current_pagination_token: None,
            next_pagination_token: None,
            result_count_this_page: None,
        }
    }
}


