/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContentPeriodCommentSummary {
    #[serde(rename = "topicId", skip_serializing_if = "Option::is_none")]
    pub topic_id: Option<i64>,
    #[serde(rename = "commentCount", skip_serializing_if = "Option::is_none")]
    pub comment_count: Option<i32>,
}

impl ContentPeriodCommentSummary {
    pub fn new() -> ContentPeriodCommentSummary {
        ContentPeriodCommentSummary {
            topic_id: None,
            comment_count: None,
        }
    }
}


