/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphNodeFeaturingStateDefinition : Nodes can have different visual states. This object represents a single visual state (\"highlight type\") that a node can be in, and the unlock expression condition to determine whether it should be set.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphNodeFeaturingStateDefinition {
    /// The node can be highlighted in a variety of ways - the game iterates through these and finds the first FeaturingState that is valid at the present moment given the Game, Account, and Character state, and renders the node in that state. See the ActivityGraphNodeHighlightType enum for possible values.
    #[serde(rename = "highlightType", skip_serializing_if = "Option::is_none")]
    pub highlight_type: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphNodeFeaturingStateDefinition {
    /// Nodes can have different visual states. This object represents a single visual state (\"highlight type\") that a node can be in, and the unlock expression condition to determine whether it should be set.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphNodeFeaturingStateDefinition {
        DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphNodeFeaturingStateDefinition {
            highlight_type: None,
        }
    }
}


