/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyResponsesDestinyProfileResponseItemComponents : Information about instanced items across all returned characters, keyed by the item's instance ID.  COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyResponsesDestinyProfileResponseItemComponents {
    #[serde(rename = "instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent>>,
    #[serde(rename = "renderData", skip_serializing_if = "Option::is_none")]
    pub render_data: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemRenderComponent>>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemStatsComponent>>,
    #[serde(rename = "sockets", skip_serializing_if = "Option::is_none")]
    pub sockets: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent>>,
    #[serde(rename = "reusablePlugs", skip_serializing_if = "Option::is_none")]
    pub reusable_plugs: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent>>,
    #[serde(rename = "plugObjectives", skip_serializing_if = "Option::is_none")]
    pub plug_objectives: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent>>,
    #[serde(rename = "talentGrids", skip_serializing_if = "Option::is_none")]
    pub talent_grids: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent>>,
    #[serde(rename = "plugStates", skip_serializing_if = "Option::is_none")]
    pub plug_states: Option<Box<crate::models::DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent>>,
    #[serde(rename = "objectives", skip_serializing_if = "Option::is_none")]
    pub objectives: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent>>,
    #[serde(rename = "perks", skip_serializing_if = "Option::is_none")]
    pub perks: Option<Box<crate::models::DictionaryComponentResponseOfint64AndDestinyItemPerksComponent>>,
}

impl DestinyResponsesDestinyProfileResponseItemComponents {
    /// Information about instanced items across all returned characters, keyed by the item's instance ID.  COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.]
    pub fn new() -> DestinyResponsesDestinyProfileResponseItemComponents {
        DestinyResponsesDestinyProfileResponseItemComponents {
            instances: None,
            render_data: None,
            stats: None,
            sockets: None,
            reusable_plugs: None,
            plug_objectives: None,
            talent_grids: None,
            plug_states: None,
            objectives: None,
            perks: None,
        }
    }
}


