/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyHistoricalStatsDestinyPostGameCarnageReportEntryExtended : Extended data extracted from the activity blob.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyHistoricalStatsDestinyPostGameCarnageReportEntryExtended {
    /// List of weapons and their perspective values.
    #[serde(rename = "weapons", skip_serializing_if = "Option::is_none")]
    pub weapons: Option<Vec<crate::models::DestinyPeriodHistoricalStatsPeriodDestinyHistoricalWeaponStats>>,
    /// Collection of stats for the player in this activity.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<::std::collections::HashMap<String, crate::models::DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsValue>>,
}

impl DestinyHistoricalStatsDestinyPostGameCarnageReportEntryExtended {
    /// Extended data extracted from the activity blob.
    pub fn new() -> DestinyHistoricalStatsDestinyPostGameCarnageReportEntryExtended {
        DestinyHistoricalStatsDestinyPostGameCarnageReportEntryExtended {
            weapons: None,
            values: None,
        }
    }
}


