/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsPeriodGroup {
    /// Period for the group. If the stat periodType is day, then this will have a specific day. If the type is monthly, then this value will be the first day of the applicable month. This value is not set when the periodType is 'all time'.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(rename = "activityDetails", skip_serializing_if = "Option::is_none")]
    pub activity_details: Option<Box<crate::models::DestinyHistoricalStatsDestinyHistoricalStatsPeriodGroupActivityDetails>>,
    /// Collection of stats for the period.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<::std::collections::HashMap<String, crate::models::DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsValue>>,
}

impl DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsPeriodGroup {
    pub fn new() -> DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsPeriodGroup {
        DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsPeriodGroup {
            period: None,
            activity_details: None,
            values: None,
        }
    }
}


