/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyInventoryItemDefinitionTalentGrid : If the item has a Talent Grid, this will be non-null and the properties of the grid defined herein. Note that, while many items still have talent grids, the only ones with meaningful Nodes still on them will be Subclass/\"Build\" items.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyInventoryItemDefinitionTalentGrid {
    /// The hash identifier of the DestinyTalentGridDefinition attached to this item.
    #[serde(rename = "talentGridHash", skip_serializing_if = "Option::is_none")]
    pub talent_grid_hash: Option<i32>,
    /// This is meant to be a subtitle for looking at the talent grid. In practice, somewhat frustratingly, this always merely says the localized word for \"Details\". Great. Maybe it'll have more if talent grids ever get used for more than builds and subclasses again.
    #[serde(rename = "itemDetailString", skip_serializing_if = "Option::is_none")]
    pub item_detail_string: Option<String>,
    /// A shortcut string identifier for the \"build\" in question, if this talent grid has an associated build. Doesn't map to anything we can expose at the moment.
    #[serde(rename = "buildName", skip_serializing_if = "Option::is_none")]
    pub build_name: Option<String>,
    /// If the talent grid implies a damage type, this is the enum value for that damage type.
    #[serde(rename = "hudDamageType", skip_serializing_if = "Option::is_none")]
    pub hud_damage_type: Option<i32>,
    /// If the talent grid has a special icon that's shown in the game UI (like builds, funny that), this is the identifier for that icon. Sadly, we don't actually get that icon right now. I'll be looking to replace this with a path to the actual icon itself.
    #[serde(rename = "hudIcon", skip_serializing_if = "Option::is_none")]
    pub hud_icon: Option<String>,
}

impl DestinyDefinitionsDestinyInventoryItemDefinitionTalentGrid {
    /// If the item has a Talent Grid, this will be non-null and the properties of the grid defined herein. Note that, while many items still have talent grids, the only ones with meaningful Nodes still on them will be Subclass/\"Build\" items.
    pub fn new() -> DestinyDefinitionsDestinyInventoryItemDefinitionTalentGrid {
        DestinyDefinitionsDestinyInventoryItemDefinitionTalentGrid {
            talent_grid_hash: None,
            item_detail_string: None,
            build_name: None,
            hud_damage_type: None,
            hud_icon: None,
        }
    }
}


