/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodArtifactsPeriodDestinyArtifactProfileScoped : Represents a Seasonal Artifact and all data related to it for the requested Account.  It can be combined with Character-scoped data for a full picture of what a character has available/has chosen, or just these settings can be used for overview information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodArtifactsPeriodDestinyArtifactProfileScoped {
    #[serde(rename = "artifactHash", skip_serializing_if = "Option::is_none")]
    pub artifact_hash: Option<i32>,
    #[serde(rename = "pointProgression", skip_serializing_if = "Option::is_none")]
    pub point_progression: Option<Box<crate::models::DestinyPeriodDestinyProgression>>,
    #[serde(rename = "pointsAcquired", skip_serializing_if = "Option::is_none")]
    pub points_acquired: Option<i32>,
    #[serde(rename = "powerBonusProgression", skip_serializing_if = "Option::is_none")]
    pub power_bonus_progression: Option<Box<crate::models::DestinyPeriodDestinyProgression>>,
    #[serde(rename = "powerBonus", skip_serializing_if = "Option::is_none")]
    pub power_bonus: Option<i32>,
}

impl DestinyPeriodArtifactsPeriodDestinyArtifactProfileScoped {
    /// Represents a Seasonal Artifact and all data related to it for the requested Account.  It can be combined with Character-scoped data for a full picture of what a character has available/has chosen, or just these settings can be used for overview information.
    pub fn new() -> DestinyPeriodArtifactsPeriodDestinyArtifactProfileScoped {
        DestinyPeriodArtifactsPeriodDestinyArtifactProfileScoped {
            artifact_hash: None,
            point_progression: None,
            points_acquired: None,
            power_bonus_progression: None,
            power_bonus: None,
        }
    }
}


