/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyItemSummaryBlockDefinition : This appears to be information used when rendering rewards. We don't currently use it on BNet.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemSummaryBlockDefinition {
    /// Apparently when rendering an item in a reward, this should be used as a sort priority. We're not doing it presently.
    #[serde(rename = "sortPriority", skip_serializing_if = "Option::is_none")]
    pub sort_priority: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemSummaryBlockDefinition {
    /// This appears to be information used when rendering rewards. We don't currently use it on BNet.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemSummaryBlockDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemSummaryBlockDefinition {
            sort_priority: None,
        }
    }
}


