/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus : An OPTIONAL component: if it makes sense to talk about this activity variant in terms of whether or not it has been completed or what progress you have made in it, this will be returned. Otherwise, this will be NULL.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus {
    /// If the activity has been \"completed\", that information will be returned here.
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<bool>,
    /// If the Activity has discrete \"phases\" that we can track, that info will be here. Otherwise, this value will be NULL. Note that this is a list and not a dictionary: the order implies the ascending order of phases or progression in this activity.
    #[serde(rename = "phases", skip_serializing_if = "Option::is_none")]
    pub phases: Option<Vec<crate::models::DestinyPeriodMilestonesPeriodDestinyMilestoneActivityPhase>>,
}

impl DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus {
    /// An OPTIONAL component: if it makes sense to talk about this activity variant in terms of whether or not it has been completed or what progress you have made in it, this will be returned. Otherwise, this will be NULL.
    pub fn new() -> DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus {
        DestinyMilestonesDestinyMilestoneActivityVariantCompletionStatus {
            completed: None,
            phases: None,
        }
    }
}


