/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryCurrentActivity : If you are playing in an activity, this is some information about it.  Note that we cannot guarantee any of this resembles what ends up in the PGCR in any way. They are sourced by two entirely separate systems with their own logic, and the one we source this data from should be considered non-authoritative in comparison.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryCurrentActivity {
    /// When the activity started.
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// If you're still in it but it \"ended\" (like when folks are dancing around the loot after they beat a boss), this is when the activity ended.
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// This is what our non-authoritative source thought the score was.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// If you have human opponents, this is the highest opposing team's score.
    #[serde(rename = "highestOpposingFactionScore", skip_serializing_if = "Option::is_none")]
    pub highest_opposing_faction_score: Option<f32>,
    /// This is how many human or poorly crafted aimbot opponents you have.
    #[serde(rename = "numberOfOpponents", skip_serializing_if = "Option::is_none")]
    pub number_of_opponents: Option<i32>,
    /// This is how many human or poorly crafted aimbots are on your team.
    #[serde(rename = "numberOfPlayers", skip_serializing_if = "Option::is_none")]
    pub number_of_players: Option<i32>,
}

impl DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryCurrentActivity {
    /// If you are playing in an activity, this is some information about it.  Note that we cannot guarantee any of this resembles what ends up in the PGCR in any way. They are sourced by two entirely separate systems with their own logic, and the one we source this data from should be considered non-authoritative in comparison.
    pub fn new() -> DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryCurrentActivity {
        DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryCurrentActivity {
            start_time: None,
            end_time: None,
            score: None,
            highest_opposing_faction_score: None,
            number_of_opponents: None,
            number_of_players: None,
        }
    }
}


