/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodResponsesPeriodDestinyCollectibleNodeDetailResponse : Returns the detailed information about a Collectible Presentation Node and any Collectibles that are direct descendants.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodResponsesPeriodDestinyCollectibleNodeDetailResponse {
    #[serde(rename = "collectibles", skip_serializing_if = "Option::is_none")]
    pub collectibles: Option<Box<crate::models::DestinyResponsesDestinyCharacterResponseCollectibles>>,
    #[serde(rename = "collectibleItemComponents", skip_serializing_if = "Option::is_none")]
    pub collectible_item_components: Option<Box<crate::models::DestinyResponsesDestinyCollectibleNodeDetailResponseCollectibleItemComponents>>,
}

impl DestinyPeriodResponsesPeriodDestinyCollectibleNodeDetailResponse {
    /// Returns the detailed information about a Collectible Presentation Node and any Collectibles that are direct descendants.
    pub fn new() -> DestinyPeriodResponsesPeriodDestinyCollectibleNodeDetailResponse {
        DestinyPeriodResponsesPeriodDestinyCollectibleNodeDetailResponse {
            collectibles: None,
            collectible_item_components: None,
        }
    }
}


