/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodPresentationPeriodDestinyPresentationNodeChildEntry {
    #[serde(rename = "presentationNodeHash", skip_serializing_if = "Option::is_none")]
    pub presentation_node_hash: Option<i32>,
    /// Use this value to sort the presentation node children in ascending order.
    #[serde(rename = "nodeDisplayPriority", skip_serializing_if = "Option::is_none")]
    pub node_display_priority: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodPresentationPeriodDestinyPresentationNodeChildEntry {
    pub fn new() -> DestinyPeriodDefinitionsPeriodPresentationPeriodDestinyPresentationNodeChildEntry {
        DestinyPeriodDefinitionsPeriodPresentationPeriodDestinyPresentationNodeChildEntry {
            presentation_node_hash: None,
            node_display_priority: None,
        }
    }
}


