/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyVendorInteractionReplyDefinition : When the interaction is replied to, Reward sites will fire and items potentially selected based on whether the given unlock expression is TRUE.  You can potentially choose one from multiple replies when replying to an interaction: this is how you get either/or rewards from vendors.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyVendorInteractionReplyDefinition {
    /// The rewards granted upon responding to the vendor.
    #[serde(rename = "itemRewardsSelection", skip_serializing_if = "Option::is_none")]
    pub item_rewards_selection: Option<i32>,
    /// The localized text for the reply.
    #[serde(rename = "reply", skip_serializing_if = "Option::is_none")]
    pub reply: Option<String>,
    /// An enum indicating the type of reply being made.
    #[serde(rename = "replyType", skip_serializing_if = "Option::is_none")]
    pub reply_type: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyVendorInteractionReplyDefinition {
    /// When the interaction is replied to, Reward sites will fire and items potentially selected based on whether the given unlock expression is TRUE.  You can potentially choose one from multiple replies when replying to an interaction: this is how you get either/or rewards from vendors.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyVendorInteractionReplyDefinition {
        DestinyPeriodDefinitionsPeriodDestinyVendorInteractionReplyDefinition {
            item_rewards_selection: None,
            reply: None,
            reply_type: None,
        }
    }
}


