/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyItemSetBlockEntryDefinition : Defines a particular entry in an ItemSet (AKA a particular Quest Step in a Quest)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemSetBlockEntryDefinition {
    /// Used for tracking which step a user reached. These values will be populated in the user's internal state, which we expose externally as a more usable DestinyQuestStatus object. If this item has been obtained, this value will be set in trackingUnlockValueHash.
    #[serde(rename = "trackingValue", skip_serializing_if = "Option::is_none")]
    pub tracking_value: Option<i32>,
    /// This is the hash identifier for a DestinyInventoryItemDefinition representing this quest step.
    #[serde(rename = "itemHash", skip_serializing_if = "Option::is_none")]
    pub item_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemSetBlockEntryDefinition {
    /// Defines a particular entry in an ItemSet (AKA a particular Quest Step in a Quest)
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemSetBlockEntryDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemSetBlockEntryDefinition {
            tracking_value: None,
            item_hash: None,
        }
    }
}


