/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodCollectiblesPeriodDestinyCollectibleStateBlock {
    #[serde(rename = "obscuredOverrideItemHash", skip_serializing_if = "Option::is_none")]
    pub obscured_override_item_hash: Option<i32>,
    #[serde(rename = "requirements", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Box<crate::models::DestinyPeriodDefinitionsPeriodPresentationPeriodDestinyPresentationNodeRequirementsBlock>>,
}

impl DestinyPeriodDefinitionsPeriodCollectiblesPeriodDestinyCollectibleStateBlock {
    pub fn new() -> DestinyPeriodDefinitionsPeriodCollectiblesPeriodDestinyCollectibleStateBlock {
        DestinyPeriodDefinitionsPeriodCollectiblesPeriodDestinyCollectibleStateBlock {
            obscured_override_item_hash: None,
            requirements: None,
        }
    }
}


