/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyVendorInteractionSackEntryDefinition : Compare this sackType to the sack identifier in the DestinyInventoryItemDefinition.vendorSackType property of items. If they match, show this sack with this interaction.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyVendorInteractionSackEntryDefinition {
    #[serde(rename = "sackType", skip_serializing_if = "Option::is_none")]
    pub sack_type: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyVendorInteractionSackEntryDefinition {
    /// Compare this sackType to the sack identifier in the DestinyInventoryItemDefinition.vendorSackType property of items. If they match, show this sack with this interaction.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyVendorInteractionSackEntryDefinition {
        DestinyPeriodDefinitionsPeriodDestinyVendorInteractionSackEntryDefinition {
            sack_type: None,
        }
    }
}


