/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinySandboxPatternDefinition {
    #[serde(rename = "patternHash", skip_serializing_if = "Option::is_none")]
    pub pattern_hash: Option<i32>,
    #[serde(rename = "patternGlobalTagIdHash", skip_serializing_if = "Option::is_none")]
    pub pattern_global_tag_id_hash: Option<i32>,
    #[serde(rename = "weaponContentGroupHash", skip_serializing_if = "Option::is_none")]
    pub weapon_content_group_hash: Option<i32>,
    #[serde(rename = "weaponTranslationGroupHash", skip_serializing_if = "Option::is_none")]
    pub weapon_translation_group_hash: Option<i32>,
    #[serde(rename = "weaponTypeHash", skip_serializing_if = "Option::is_none")]
    pub weapon_type_hash: Option<i32>,
    #[serde(rename = "weaponType", skip_serializing_if = "Option::is_none")]
    pub weapon_type: Option<i32>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<crate::models::DestinyPeriodDefinitionsPeriodDestinyArrangementRegionFilterDefinition>>,
    /// The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<i32>,
    /// The index of the entity as it was found in the investment tables.
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    /// If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    #[serde(rename = "redacted", skip_serializing_if = "Option::is_none")]
    pub redacted: Option<bool>,
}

impl DestinyPeriodDefinitionsPeriodDestinySandboxPatternDefinition {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinySandboxPatternDefinition {
        DestinyPeriodDefinitionsPeriodDestinySandboxPatternDefinition {
            pattern_hash: None,
            pattern_global_tag_id_hash: None,
            weapon_content_group_hash: None,
            weapon_translation_group_hash: None,
            weapon_type_hash: None,
            weapon_type: None,
            filters: None,
            hash: None,
            index: None,
            redacted: None,
        }
    }
}


