/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodCharacterPeriodDestinyCharacterPeerView : A minimal view of a character's equipped items, for the purpose of rendering a summary screen or showing the character in 3D.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodCharacterPeriodDestinyCharacterPeerView {
    #[serde(rename = "equipment", skip_serializing_if = "Option::is_none")]
    pub equipment: Option<Vec<crate::models::DestinyPeriodCharacterPeriodDestinyItemPeerView>>,
}

impl DestinyPeriodCharacterPeriodDestinyCharacterPeerView {
    /// A minimal view of a character's equipped items, for the purpose of rendering a summary screen or showing the character in 3D.
    pub fn new() -> DestinyPeriodCharacterPeriodDestinyCharacterPeerView {
        DestinyPeriodCharacterPeriodDestinyCharacterPeerView {
            equipment: None,
        }
    }
}


