/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyItemGearsetBlockDefinition : If an item has a related gearset, this is the list of items in that set, and an unlock expression that evaluates to a number representing the progress toward gearset completion (a very rare use for unlock expressions!)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemGearsetBlockDefinition {
    /// The maximum possible number of items that can be collected.
    #[serde(rename = "trackingValueMax", skip_serializing_if = "Option::is_none")]
    pub tracking_value_max: Option<i32>,
    /// The list of hashes for items in the gearset. Use them to look up DestinyInventoryItemDefinition entries for the items in the set.
    #[serde(rename = "itemList", skip_serializing_if = "Option::is_none")]
    pub item_list: Option<Vec<i32>>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemGearsetBlockDefinition {
    /// If an item has a related gearset, this is the list of items in that set, and an unlock expression that evaluates to a number representing the progress toward gearset completion (a very rare use for unlock expressions!)
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemGearsetBlockDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemGearsetBlockDefinition {
            tracking_value_max: None,
            item_list: None,
        }
    }
}


