/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordExpirationBlock : If this record has an expiration after which it cannot be earned, this is some information about that expiration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordExpirationBlock {
    #[serde(rename = "hasExpiration", skip_serializing_if = "Option::is_none")]
    pub has_expiration: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

impl DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordExpirationBlock {
    /// If this record has an expiration after which it cannot be earned, this is some information about that expiration.
    pub fn new() -> DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordExpirationBlock {
        DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordExpirationBlock {
            has_expiration: None,
            description: None,
            icon: None,
        }
    }
}


