/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordIntervalObjective {
    #[serde(rename = "intervalObjectiveHash", skip_serializing_if = "Option::is_none")]
    pub interval_objective_hash: Option<i32>,
    #[serde(rename = "intervalScoreValue", skip_serializing_if = "Option::is_none")]
    pub interval_score_value: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordIntervalObjective {
    pub fn new() -> DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordIntervalObjective {
        DestinyPeriodDefinitionsPeriodRecordsPeriodDestinyRecordIntervalObjective {
            interval_objective_hash: None,
            interval_score_value: None,
        }
    }
}


