/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodRequestsPeriodActionsPeriodDestinyPostmasterTransferRequest {
    #[serde(rename = "itemReferenceHash", skip_serializing_if = "Option::is_none")]
    pub item_reference_hash: Option<i32>,
    #[serde(rename = "stackSize", skip_serializing_if = "Option::is_none")]
    pub stack_size: Option<i32>,
    /// The instance ID of the item for this action request.
    #[serde(rename = "itemId", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<i64>,
    #[serde(rename = "characterId", skip_serializing_if = "Option::is_none")]
    pub character_id: Option<i64>,
    #[serde(rename = "membershipType", skip_serializing_if = "Option::is_none")]
    pub membership_type: Option<i32>,
}

impl DestinyPeriodRequestsPeriodActionsPeriodDestinyPostmasterTransferRequest {
    pub fn new() -> DestinyPeriodRequestsPeriodActionsPeriodDestinyPostmasterTransferRequest {
        DestinyPeriodRequestsPeriodActionsPeriodDestinyPostmasterTransferRequest {
            item_reference_hash: None,
            stack_size: None,
            item_id: None,
            character_id: None,
            membership_type: None,
        }
    }
}


