/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemSocketEntryPlugItemRandomizedDefinition {
    #[serde(rename = "craftingRequirements", skip_serializing_if = "Option::is_none")]
    pub crafting_requirements: Option<Box<crate::models::DestinyPeriodDefinitionsPeriodDestinyPlugItemCraftingRequirements>>,
    /// Indicates if the plug can be rolled on the current version of the item. For example, older versions of weapons may have plug rolls that are no longer possible on the current versions.
    #[serde(rename = "currentlyCanRoll", skip_serializing_if = "Option::is_none")]
    pub currently_can_roll: Option<bool>,
    /// The hash identifier of a DestinyInventoryItemDefinition representing the plug that can be inserted.
    #[serde(rename = "plugItemHash", skip_serializing_if = "Option::is_none")]
    pub plug_item_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemSocketEntryPlugItemRandomizedDefinition {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemSocketEntryPlugItemRandomizedDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemSocketEntryPlugItemRandomizedDefinition {
            crafting_requirements: None,
            currently_can_roll: None,
            plug_item_hash: None,
        }
    }
}


