/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyVendorItemDefinitionAction : The action to be performed when purchasing the item, if it's not just \"buy\".



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyVendorItemDefinitionAction {
    #[serde(rename = "executeSeconds", skip_serializing_if = "Option::is_none")]
    pub execute_seconds: Option<f32>,
    #[serde(rename = "isPositive", skip_serializing_if = "Option::is_none")]
    pub is_positive: Option<bool>,
}

impl DestinyDefinitionsDestinyVendorItemDefinitionAction {
    /// The action to be performed when purchasing the item, if it's not just \"buy\".
    pub fn new() -> DestinyDefinitionsDestinyVendorItemDefinitionAction {
        DestinyDefinitionsDestinyVendorItemDefinitionAction {
            execute_seconds: None,
            is_positive: None,
        }
    }
}


