/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyGearArtArrangementReference {
    #[serde(rename = "classHash", skip_serializing_if = "Option::is_none")]
    pub class_hash: Option<i32>,
    #[serde(rename = "artArrangementHash", skip_serializing_if = "Option::is_none")]
    pub art_arrangement_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyGearArtArrangementReference {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyGearArtArrangementReference {
        DestinyPeriodDefinitionsPeriodDestinyGearArtArrangementReference {
            class_hash: None,
            art_arrangement_hash: None,
        }
    }
}


