/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodArtifactsPeriodDestinyArtifactTierDefinition {
    /// An identifier, unique within the Artifact, for this specific tier.
    #[serde(rename = "tierHash", skip_serializing_if = "Option::is_none")]
    pub tier_hash: Option<i32>,
    /// The human readable title of this tier, if any.
    #[serde(rename = "displayTitle", skip_serializing_if = "Option::is_none")]
    pub display_title: Option<String>,
    /// A string representing the localized minimum requirement text for this Tier, if any.
    #[serde(rename = "progressRequirementMessage", skip_serializing_if = "Option::is_none")]
    pub progress_requirement_message: Option<String>,
    /// The items that can be earned within this tier.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::DestinyPeriodDefinitionsPeriodArtifactsPeriodDestinyArtifactTierItemDefinition>>,
    /// The minimum number of \"unlock points\" that you must have used before you can unlock items from this tier.
    #[serde(rename = "minimumUnlockPointsUsedRequirement", skip_serializing_if = "Option::is_none")]
    pub minimum_unlock_points_used_requirement: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodArtifactsPeriodDestinyArtifactTierDefinition {
    pub fn new() -> DestinyPeriodDefinitionsPeriodArtifactsPeriodDestinyArtifactTierDefinition {
        DestinyPeriodDefinitionsPeriodArtifactsPeriodDestinyArtifactTierDefinition {
            tier_hash: None,
            display_title: None,
            progress_requirement_message: None,
            items: None,
            minimum_unlock_points_used_requirement: None,
        }
    }
}


