/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDestinyUnlockStatus : Indicates the status of an \"Unlock Flag\" on a Character or Profile.  These are individual bits of state that can be either set or not set, and sometimes provide interesting human-readable information in their related DestinyUnlockDefinition.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDestinyUnlockStatus {
    /// The hash identifier for the Unlock Flag. Use to lookup DestinyUnlockDefinition for static data. Not all unlocks have human readable data - in fact, most don't. But when they do, it can be very useful to show. Even if they don't have human readable data, you might be able to infer the meaning of an unlock flag with a bit of experimentation...
    #[serde(rename = "unlockHash", skip_serializing_if = "Option::is_none")]
    pub unlock_hash: Option<i32>,
    /// Whether the unlock flag is set.
    #[serde(rename = "isSet", skip_serializing_if = "Option::is_none")]
    pub is_set: Option<bool>,
}

impl DestinyPeriodDestinyUnlockStatus {
    /// Indicates the status of an \"Unlock Flag\" on a Character or Profile.  These are individual bits of state that can be either set or not set, and sometimes provide interesting human-readable information in their related DestinyUnlockDefinition.
    pub fn new() -> DestinyPeriodDestinyUnlockStatus {
        DestinyPeriodDestinyUnlockStatus {
            unlock_hash: None,
            is_set: None,
        }
    }
}


