/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemCraftingBlockBonusPlugDefinition {
    #[serde(rename = "socketTypeHash", skip_serializing_if = "Option::is_none")]
    pub socket_type_hash: Option<i32>,
    #[serde(rename = "plugItemHash", skip_serializing_if = "Option::is_none")]
    pub plug_item_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemCraftingBlockBonusPlugDefinition {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemCraftingBlockBonusPlugDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemCraftingBlockBonusPlugDefinition {
            socket_type_hash: None,
            plug_item_hash: None,
        }
    }
}


