/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsRequestEntry : Represents all of the data related to a single plug to be inserted.  Note that, while you *can* point to a socket that represents infusion, you will receive an error if you attempt to do so. Come on guys, let's play nice.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsRequestEntry {
    /// The index into the socket array, which identifies the specific socket being operated on. We also need to know the socketArrayType in order to uniquely identify the socket.  Don't point to or try to insert a plug into an infusion socket. It won't work.
    #[serde(rename = "socketIndex", skip_serializing_if = "Option::is_none")]
    pub socket_index: Option<i32>,
    /// This property, combined with the socketIndex, tells us which socket we are referring to (since operations can be performed on both Intrinsic and \"default\" sockets, and they occupy different arrays in the Inventory Item Definition). I know, I know. Don't give me that look.
    #[serde(rename = "socketArrayType", skip_serializing_if = "Option::is_none")]
    pub socket_array_type: Option<i32>,
    /// Plugs are never instanced (except in infusion). So with the hash alone, we should be able to: 1) Infer whether the player actually needs to have the item, or if it's a reusable plug 2) Perform any operation needed to use the Plug, including removing the plug item and running reward sheets.
    #[serde(rename = "plugItemHash", skip_serializing_if = "Option::is_none")]
    pub plug_item_hash: Option<i32>,
}

impl DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsRequestEntry {
    /// Represents all of the data related to a single plug to be inserted.  Note that, while you *can* point to a socket that represents infusion, you will receive an error if you attempt to do so. Come on guys, let's play nice.
    pub fn new() -> DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsRequestEntry {
        DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsRequestEntry {
            socket_index: None,
            socket_array_type: None,
            plug_item_hash: None,
        }
    }
}


