/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodMilestonesPeriodDestinyMilestoneRewardCategory : Represents a category of \"summary\" rewards that can be earned for the Milestone regardless of specific quest rewards that can be earned.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodMilestonesPeriodDestinyMilestoneRewardCategory {
    /// Look up the relevant DestinyMilestoneDefinition, and then use rewardCategoryHash to look up the category info in DestinyMilestoneDefinition.rewards.
    #[serde(rename = "rewardCategoryHash", skip_serializing_if = "Option::is_none")]
    pub reward_category_hash: Option<i32>,
    /// The individual reward entries for this category, and their status.
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::models::DestinyPeriodMilestonesPeriodDestinyMilestoneRewardEntry>>,
}

impl DestinyPeriodMilestonesPeriodDestinyMilestoneRewardCategory {
    /// Represents a category of \"summary\" rewards that can be earned for the Milestone regardless of specific quest rewards that can be earned.
    pub fn new() -> DestinyPeriodMilestonesPeriodDestinyMilestoneRewardCategory {
        DestinyPeriodMilestonesPeriodDestinyMilestoneRewardCategory {
            reward_category_hash: None,
            entries: None,
        }
    }
}


