/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyVendorServiceDefinition : When a vendor provides services, this is the localized name of those services.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyVendorServiceDefinition {
    /// The localized name of a service provided.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl DestinyPeriodDefinitionsPeriodDestinyVendorServiceDefinition {
    /// When a vendor provides services, this is the localized name of those services.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyVendorServiceDefinition {
        DestinyPeriodDefinitionsPeriodDestinyVendorServiceDefinition {
            name: None,
        }
    }
}


