/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyTalentNodeDefinitionRandomActivationRequirement : At one point, you were going to be able to repurchase talent nodes that had random steps, to \"re-roll\" the current step of the node (and thus change the properties of your item). This was to be the activation requirement for performing that re-roll.  The system still exists to do this, as far as I know, so it may yet come back around!



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyTalentNodeDefinitionRandomActivationRequirement {
    /// The Progression level on the Talent Grid required to activate this node.  See DestinyTalentGridDefinition.progressionHash for the related Progression, and read DestinyProgressionDefinition's documentation to learn more about Progressions.
    #[serde(rename = "gridLevel", skip_serializing_if = "Option::is_none")]
    pub grid_level: Option<i32>,
    /// The list of hash identifiers for material requirement sets: materials that are required for the node to be activated. See DestinyMaterialRequirementSetDefinition for more information about material requirements.  In this case, only a single DestinyMaterialRequirementSetDefinition will be chosen from this list, and we won't know which one will be chosen until an instance of the item is created.
    #[serde(rename = "materialRequirementHashes", skip_serializing_if = "Option::is_none")]
    pub material_requirement_hashes: Option<Vec<i32>>,
}

impl DestinyDefinitionsDestinyTalentNodeDefinitionRandomActivationRequirement {
    /// At one point, you were going to be able to repurchase talent nodes that had random steps, to \"re-roll\" the current step of the node (and thus change the properties of your item). This was to be the activation requirement for performing that re-roll.  The system still exists to do this, as far as I know, so it may yet come back around!
    pub fn new() -> DestinyDefinitionsDestinyTalentNodeDefinitionRandomActivationRequirement {
        DestinyDefinitionsDestinyTalentNodeDefinitionRandomActivationRequirement {
            grid_level: None,
            material_requirement_hashes: None,
        }
    }
}


