/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodItemsPeriodDestinyParentItemOverride {
    #[serde(rename = "additionalEquipRequirementsDisplayStrings", skip_serializing_if = "Option::is_none")]
    pub additional_equip_requirements_display_strings: Option<Vec<String>>,
    #[serde(rename = "pipIcon", skip_serializing_if = "Option::is_none")]
    pub pip_icon: Option<String>,
}

impl DestinyPeriodDefinitionsPeriodItemsPeriodDestinyParentItemOverride {
    pub fn new() -> DestinyPeriodDefinitionsPeriodItemsPeriodDestinyParentItemOverride {
        DestinyPeriodDefinitionsPeriodItemsPeriodDestinyParentItemOverride {
            additional_equip_requirements_display_strings: None,
            pip_icon: None,
        }
    }
}


