/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyActivityDefinitionMatchmaking : This block of data provides information about the Activity's matchmaking attributes: how many people can join and such.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyActivityDefinitionMatchmaking {
    /// If TRUE, the activity is matchmade. Otherwise, it requires explicit forming of a party.
    #[serde(rename = "isMatchmade", skip_serializing_if = "Option::is_none")]
    pub is_matchmade: Option<bool>,
    /// The minimum # of people in the fireteam for the activity to launch.
    #[serde(rename = "minParty", skip_serializing_if = "Option::is_none")]
    pub min_party: Option<i32>,
    /// The maximum # of people allowed in a Fireteam.
    #[serde(rename = "maxParty", skip_serializing_if = "Option::is_none")]
    pub max_party: Option<i32>,
    /// The maximum # of people allowed across all teams in the activity.
    #[serde(rename = "maxPlayers", skip_serializing_if = "Option::is_none")]
    pub max_players: Option<i32>,
    /// If true, you have to Solemnly Swear to be up to Nothing But Good(tm) to play.
    #[serde(rename = "requiresGuardianOath", skip_serializing_if = "Option::is_none")]
    pub requires_guardian_oath: Option<bool>,
}

impl DestinyDefinitionsDestinyActivityDefinitionMatchmaking {
    /// This block of data provides information about the Activity's matchmaking attributes: how many people can join and such.
    pub fn new() -> DestinyDefinitionsDestinyActivityDefinitionMatchmaking {
        DestinyDefinitionsDestinyActivityDefinitionMatchmaking {
            is_matchmade: None,
            min_party: None,
            max_party: None,
            max_players: None,
            requires_guardian_oath: None,
        }
    }
}


