/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodMilestonesPeriodDestinyPublicMilestoneVendor {
    /// The hash identifier of the Vendor related to this Milestone. You can show useful things from this, such as thier Faction icon or whatever you might care about.
    #[serde(rename = "vendorHash", skip_serializing_if = "Option::is_none")]
    pub vendor_hash: Option<i32>,
    /// If this vendor is featuring a specific item for this event, this will be the hash identifier of that item. I'm taking bets now on how long we go before this needs to be a list or some other, more complex representation instead and I deprecate this too. I'm going to go with 5 months. Calling it now, 2017-09-14 at 9:46pm PST.
    #[serde(rename = "previewItemHash", skip_serializing_if = "Option::is_none")]
    pub preview_item_hash: Option<i32>,
}

impl DestinyPeriodMilestonesPeriodDestinyPublicMilestoneVendor {
    pub fn new() -> DestinyPeriodMilestonesPeriodDestinyPublicMilestoneVendor {
        DestinyPeriodMilestonesPeriodDestinyPublicMilestoneVendor {
            vendor_hash: None,
            preview_item_hash: None,
        }
    }
}


