/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodCommonPeriodDestinyPositionDefinition {
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<i32>,
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<i32>,
    #[serde(rename = "z", skip_serializing_if = "Option::is_none")]
    pub z: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodCommonPeriodDestinyPositionDefinition {
    pub fn new() -> DestinyPeriodDefinitionsPeriodCommonPeriodDestinyPositionDefinition {
        DestinyPeriodDefinitionsPeriodCommonPeriodDestinyPositionDefinition {
            x: None,
            y: None,
            z: None,
        }
    }
}


