/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodConfigPeriodGearAssetDataBaseDefinition {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl DestinyPeriodConfigPeriodGearAssetDataBaseDefinition {
    pub fn new() -> DestinyPeriodConfigPeriodGearAssetDataBaseDefinition {
        DestinyPeriodConfigPeriodGearAssetDataBaseDefinition {
            version: None,
            path: None,
        }
    }
}


