/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodMilestonesPeriodDestinyMilestoneContent : Represents localized, extended content related to Milestones. This is intentionally returned by a separate endpoint and not with Character-level Milestone data because we do not put localized data into standard Destiny responses, both for brevity of response and for caching purposes. If you really need this data, hit the Milestone Content endpoint.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodMilestonesPeriodDestinyMilestoneContent {
    /// The \"About this Milestone\" text from the Firehose.
    #[serde(rename = "about", skip_serializing_if = "Option::is_none")]
    pub about: Option<String>,
    /// The Current Status of the Milestone, as driven by the Firehose.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// A list of tips, provided by the Firehose.
    #[serde(rename = "tips", skip_serializing_if = "Option::is_none")]
    pub tips: Option<Vec<String>>,
    /// If DPS has defined items related to this Milestone, they can categorize those items in the Firehose. That data will then be returned as item categories here.
    #[serde(rename = "itemCategories", skip_serializing_if = "Option::is_none")]
    pub item_categories: Option<Vec<crate::models::DestinyPeriodMilestonesPeriodDestinyMilestoneContentItemCategory>>,
}

impl DestinyPeriodMilestonesPeriodDestinyMilestoneContent {
    /// Represents localized, extended content related to Milestones. This is intentionally returned by a separate endpoint and not with Character-level Milestone data because we do not put localized data into standard Destiny responses, both for brevity of response and for caching purposes. If you really need this data, hit the Milestone Content endpoint.
    pub fn new() -> DestinyPeriodMilestonesPeriodDestinyMilestoneContent {
        DestinyPeriodMilestonesPeriodDestinyMilestoneContent {
            about: None,
            status: None,
            tips: None,
            item_categories: None,
        }
    }
}


