/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodComponentsPeriodRecordsPeriodDestinyProfileRecordsComponent {
    /// Your 'active' Triumphs score, maintained for backwards compatibility.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
    /// Your 'active' Triumphs score.
    #[serde(rename = "activeScore", skip_serializing_if = "Option::is_none")]
    pub active_score: Option<i32>,
    /// Your 'legacy' Triumphs score.
    #[serde(rename = "legacyScore", skip_serializing_if = "Option::is_none")]
    pub legacy_score: Option<i32>,
    /// Your 'lifetime' Triumphs score.
    #[serde(rename = "lifetimeScore", skip_serializing_if = "Option::is_none")]
    pub lifetime_score: Option<i32>,
    /// If this profile is tracking a record, this is the hash identifier of the record it is tracking.
    #[serde(rename = "trackedRecordHash", skip_serializing_if = "Option::is_none")]
    pub tracked_record_hash: Option<i32>,
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<::std::collections::HashMap<String, crate::models::DestinyPeriodComponentsPeriodRecordsPeriodDestinyRecordComponent>>,
    /// The hash for the root presentation node definition of Triumph categories.
    #[serde(rename = "recordCategoriesRootNodeHash", skip_serializing_if = "Option::is_none")]
    pub record_categories_root_node_hash: Option<i32>,
    /// The hash for the root presentation node definition of Triumph Seals.
    #[serde(rename = "recordSealsRootNodeHash", skip_serializing_if = "Option::is_none")]
    pub record_seals_root_node_hash: Option<i32>,
}

impl DestinyPeriodComponentsPeriodRecordsPeriodDestinyProfileRecordsComponent {
    pub fn new() -> DestinyPeriodComponentsPeriodRecordsPeriodDestinyProfileRecordsComponent {
        DestinyPeriodComponentsPeriodRecordsPeriodDestinyProfileRecordsComponent {
            score: None,
            active_score: None,
            legacy_score: None,
            lifetime_score: None,
            tracked_record_hash: None,
            records: None,
            record_categories_root_node_hash: None,
            record_seals_root_node_hash: None,
        }
    }
}


