/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodHistoricalStatsPeriodDestinyHistoricalWeaponStats {
    /// The hash ID of the item definition that describes the weapon.
    #[serde(rename = "referenceId", skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<i32>,
    /// Collection of stats for the period.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<::std::collections::HashMap<String, crate::models::DestinyPeriodHistoricalStatsPeriodDestinyHistoricalStatsValue>>,
}

impl DestinyPeriodHistoricalStatsPeriodDestinyHistoricalWeaponStats {
    pub fn new() -> DestinyPeriodHistoricalStatsPeriodDestinyHistoricalWeaponStats {
        DestinyPeriodHistoricalStatsPeriodDestinyHistoricalWeaponStats {
            reference_id: None,
            values: None,
        }
    }
}


