/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDestinyPresentationScreenStyle : A hint for what screen should be shown when this presentation node is clicked into. How you use this is your UI is up to you.

/// A hint for what screen should be shown when this presentation node is clicked into. How you use this is your UI is up to you.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DestinyPeriodDestinyPresentationScreenStyle {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,

}

impl ToString for DestinyPeriodDestinyPresentationScreenStyle {
    fn to_string(&self) -> String {
        match self {
            Self::Variant0 => String::from("0"),
            Self::Variant1 => String::from("1"),
            Self::Variant2 => String::from("2"),
        }
    }
}

impl Default for DestinyPeriodDestinyPresentationScreenStyle {
    fn default() -> DestinyPeriodDestinyPresentationScreenStyle {
        Self::Variant0
    }
}




