/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodMilestonesPeriodDestinyMilestoneActivityVariantDefinition : Represents a variant on an activity for a Milestone: a specific difficulty tier, or a specific activity variant for example.  These will often have more specific details, such as an associated Guided Game, progression steps, tier-specific rewards, and custom values.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodMilestonesPeriodDestinyMilestoneActivityVariantDefinition {
    /// The hash to use for looking up the variant Activity's definition (DestinyActivityDefinition), where you can find its distinguishing characteristics such as difficulty level and recommended light level.   Frequently, that will be the only distinguishing characteristics in practice, which is somewhat of a bummer.
    #[serde(rename = "activityHash", skip_serializing_if = "Option::is_none")]
    pub activity_hash: Option<i32>,
    /// If you care to do so, render the variants in the order prescribed by this value.  When you combine live Milestone data with the definition, the order becomes more useful because you'll be cross-referencing between the definition and live data.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodMilestonesPeriodDestinyMilestoneActivityVariantDefinition {
    /// Represents a variant on an activity for a Milestone: a specific difficulty tier, or a specific activity variant for example.  These will often have more specific details, such as an associated Guided Game, progression steps, tier-specific rewards, and custom values.
    pub fn new() -> DestinyPeriodDefinitionsPeriodMilestonesPeriodDestinyMilestoneActivityVariantDefinition {
        DestinyPeriodDefinitionsPeriodMilestonesPeriodDestinyMilestoneActivityVariantDefinition {
            activity_hash: None,
            order: None,
        }
    }
}


