/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyVendorCategoryEntryDefinition : This is the definition for a single Vendor Category, into which Sale Items are grouped.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyVendorCategoryEntryDefinition {
    /// The index of the category in the original category definitions for the vendor.
    #[serde(rename = "categoryIndex", skip_serializing_if = "Option::is_none")]
    pub category_index: Option<i32>,
    /// Used in sorting items in vendors... but there's a lot more to it. Just go with the order provided in the itemIndexes property on the DestinyVendorCategoryComponent instead, it should be more reliable than trying to recalculate it yourself.
    #[serde(rename = "sortValue", skip_serializing_if = "Option::is_none")]
    pub sort_value: Option<i32>,
    /// The hashed identifier for the category.
    #[serde(rename = "categoryHash", skip_serializing_if = "Option::is_none")]
    pub category_hash: Option<i32>,
    /// The amount of items that will be available when this category is shown.
    #[serde(rename = "quantityAvailable", skip_serializing_if = "Option::is_none")]
    pub quantity_available: Option<i32>,
    /// If items aren't up for sale in this category, should we still show them (greyed out)?
    #[serde(rename = "showUnavailableItems", skip_serializing_if = "Option::is_none")]
    pub show_unavailable_items: Option<bool>,
    /// If you don't have the currency required to buy items from this category, should the items be hidden?
    #[serde(rename = "hideIfNoCurrency", skip_serializing_if = "Option::is_none")]
    pub hide_if_no_currency: Option<bool>,
    /// True if this category doesn't allow purchases.
    #[serde(rename = "hideFromRegularPurchase", skip_serializing_if = "Option::is_none")]
    pub hide_from_regular_purchase: Option<bool>,
    /// The localized string for making purchases from this category, if it is different from the vendor's string for purchasing.
    #[serde(rename = "buyStringOverride", skip_serializing_if = "Option::is_none")]
    pub buy_string_override: Option<String>,
    /// If the category is disabled, this is the localized description to show.
    #[serde(rename = "disabledDescription", skip_serializing_if = "Option::is_none")]
    pub disabled_description: Option<String>,
    /// The localized title of the category.
    #[serde(rename = "displayTitle", skip_serializing_if = "Option::is_none")]
    pub display_title: Option<String>,
    #[serde(rename = "overlay", skip_serializing_if = "Option::is_none")]
    pub overlay: Option<Box<crate::models::DestinyDefinitionsDestinyVendorCategoryEntryDefinitionOverlay>>,
    /// A shortcut for the vendor item indexes sold under this category. Saves us from some expensive reorganization at runtime.
    #[serde(rename = "vendorItemIndexes", skip_serializing_if = "Option::is_none")]
    pub vendor_item_indexes: Option<Vec<i32>>,
    /// Sometimes a category isn't actually used to sell items, but rather to preview them. This implies different UI (and manual placement of the category in the UI) in the game, and special treatment.
    #[serde(rename = "isPreview", skip_serializing_if = "Option::is_none")]
    pub is_preview: Option<bool>,
    /// If true, this category only displays items: you can't purchase anything in them.
    #[serde(rename = "isDisplayOnly", skip_serializing_if = "Option::is_none")]
    pub is_display_only: Option<bool>,
    #[serde(rename = "resetIntervalMinutesOverride", skip_serializing_if = "Option::is_none")]
    pub reset_interval_minutes_override: Option<i32>,
    #[serde(rename = "resetOffsetMinutesOverride", skip_serializing_if = "Option::is_none")]
    pub reset_offset_minutes_override: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyVendorCategoryEntryDefinition {
    /// This is the definition for a single Vendor Category, into which Sale Items are grouped.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyVendorCategoryEntryDefinition {
        DestinyPeriodDefinitionsPeriodDestinyVendorCategoryEntryDefinition {
            category_index: None,
            sort_value: None,
            category_hash: None,
            quantity_available: None,
            show_unavailable_items: None,
            hide_if_no_currency: None,
            hide_from_regular_purchase: None,
            buy_string_override: None,
            disabled_description: None,
            display_title: None,
            overlay: None,
            vendor_item_indexes: None,
            is_preview: None,
            is_display_only: None,
            reset_interval_minutes_override: None,
            reset_offset_minutes_override: None,
        }
    }
}


