/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyActivityGuidedBlockDefinition : Guided Game information for this activity.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyActivityGuidedBlockDefinition {
    /// The maximum amount of people that can be in the waiting lobby.
    #[serde(rename = "guidedMaxLobbySize", skip_serializing_if = "Option::is_none")]
    pub guided_max_lobby_size: Option<i32>,
    /// The minimum amount of people that can be in the waiting lobby.
    #[serde(rename = "guidedMinLobbySize", skip_serializing_if = "Option::is_none")]
    pub guided_min_lobby_size: Option<i32>,
    /// If -1, the guided group cannot be disbanded. Otherwise, take the total # of players in the activity and subtract this number: that is the total # of votes needed for the guided group to disband.
    #[serde(rename = "guidedDisbandCount", skip_serializing_if = "Option::is_none")]
    pub guided_disband_count: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyActivityGuidedBlockDefinition {
    /// Guided Game information for this activity.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyActivityGuidedBlockDefinition {
        DestinyPeriodDefinitionsPeriodDestinyActivityGuidedBlockDefinition {
            guided_max_lobby_size: None,
            guided_min_lobby_size: None,
            guided_disband_count: None,
        }
    }
}


