/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyArtDyeReference {
    #[serde(rename = "artDyeChannelHash", skip_serializing_if = "Option::is_none")]
    pub art_dye_channel_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDestinyArtDyeReference {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyArtDyeReference {
        DestinyPeriodDefinitionsPeriodDestinyArtDyeReference {
            art_dye_channel_hash: None,
        }
    }
}


