/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodSocketsPeriodDestinyInsertPlugActionDefinition : Data related to what happens while a plug is being inserted, mostly for UI purposes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodSocketsPeriodDestinyInsertPlugActionDefinition {
    /// How long it takes for the Plugging of the item to be completed once it is initiated, if you care.
    #[serde(rename = "actionExecuteSeconds", skip_serializing_if = "Option::is_none")]
    pub action_execute_seconds: Option<i32>,
    /// The type of action being performed when you act on this Socket Type. The most common value is \"insert plug\", but there are others as well (for instance, a \"Masterwork\" socket may allow for Re-initialization, and an Infusion socket allows for items to be consumed to upgrade the item)
    #[serde(rename = "actionType", skip_serializing_if = "Option::is_none")]
    pub action_type: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodSocketsPeriodDestinyInsertPlugActionDefinition {
    /// Data related to what happens while a plug is being inserted, mostly for UI purposes.
    pub fn new() -> DestinyPeriodDefinitionsPeriodSocketsPeriodDestinyInsertPlugActionDefinition {
        DestinyPeriodDefinitionsPeriodSocketsPeriodDestinyInsertPlugActionDefinition {
            action_execute_seconds: None,
            action_type: None,
        }
    }
}


