/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryPartyMember : This is some bare minimum information about a party member in a Fireteam. Unfortunately, without great computational expense on our side we can only get at the data contained here. I'd like to give you a character ID for example, but we don't have it. But we do have these three pieces of information. May they help you on your quest to show meaningful data about current Fireteams.  Notably, we don't and can't feasibly return info on characters. If you can, try to use just the data below for your UI and purposes. Only hit us with further queries if you absolutely must know the character ID of the currently playing character. Pretty please with sugar on top.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryPartyMember {
    /// The Membership ID that matches the party member.
    #[serde(rename = "membershipId", skip_serializing_if = "Option::is_none")]
    pub membership_id: Option<i64>,
    /// The identifier for the DestinyInventoryItemDefinition of the player's emblem.
    #[serde(rename = "emblemHash", skip_serializing_if = "Option::is_none")]
    pub emblem_hash: Option<i32>,
    /// The player's last known display name.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// A Flags Enumeration value indicating the states that the player is in relevant to being on a fireteam.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
}

impl DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryPartyMember {
    /// This is some bare minimum information about a party member in a Fireteam. Unfortunately, without great computational expense on our side we can only get at the data contained here. I'd like to give you a character ID for example, but we don't have it. But we do have these three pieces of information. May they help you on your quest to show meaningful data about current Fireteams.  Notably, we don't and can't feasibly return info on characters. If you can, try to use just the data below for your UI and purposes. Only hit us with further queries if you absolutely must know the character ID of the currently playing character. Pretty please with sugar on top.
    pub fn new() -> DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryPartyMember {
        DestinyPeriodComponentsPeriodProfilesPeriodDestinyProfileTransitoryPartyMember {
            membership_id: None,
            emblem_hash: None,
            display_name: None,
            status: None,
        }
    }
}


