/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyResponsesDestinyItemResponseTalentGrid : Information about the talent grid attached to the item. Talent nodes can provide a variety of benefits and abilities, and in Destiny 2 are used almost exclusively for the character's \"Builds\".  COMPONENT TYPE: ItemTalentGrids



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyResponsesDestinyItemResponseTalentGrid {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::DestinyPeriodEntitiesPeriodItemsPeriodDestinyItemTalentGridComponent>>,
    #[serde(rename = "privacy", skip_serializing_if = "Option::is_none")]
    pub privacy: Option<i32>,
    /// If true, this component is disabled.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
}

impl DestinyResponsesDestinyItemResponseTalentGrid {
    /// Information about the talent grid attached to the item. Talent nodes can provide a variety of benefits and abilities, and in Destiny 2 are used almost exclusively for the character's \"Builds\".  COMPONENT TYPE: ItemTalentGrids
    pub fn new() -> DestinyResponsesDestinyItemResponseTalentGrid {
        DestinyResponsesDestinyItemResponseTalentGrid {
            data: None,
            privacy: None,
            disabled: None,
        }
    }
}


