/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyTalentNodeCategory : An artificial construct provided by Bungie.Net, where we attempt to group talent nodes by functionality.  This is a single set of references to Talent Nodes that share a common trait or purpose.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyTalentNodeCategory {
    /// Mostly just for debug purposes, but if you find it useful you can have it. This is BNet's manually created identifier for this category.
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    /// If true, we found the localized content in a related DestinyLoreDefinition instead of local BNet localization files. This is mostly for ease of my own future investigations.
    #[serde(rename = "isLoreDriven", skip_serializing_if = "Option::is_none")]
    pub is_lore_driven: Option<bool>,
    #[serde(rename = "displayProperties", skip_serializing_if = "Option::is_none")]
    pub display_properties: Option<Box<crate::models::DestinyDefinitionsDestinyTalentNodeCategoryDisplayProperties>>,
    /// The set of all hash identifiers for Talent Nodes (DestinyTalentNodeDefinition) in this Talent Grid that are part of this Category.
    #[serde(rename = "nodeHashes", skip_serializing_if = "Option::is_none")]
    pub node_hashes: Option<Vec<i32>>,
}

impl DestinyPeriodDefinitionsPeriodDestinyTalentNodeCategory {
    /// An artificial construct provided by Bungie.Net, where we attempt to group talent nodes by functionality.  This is a single set of references to Talent Nodes that share a common trait or purpose.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyTalentNodeCategory {
        DestinyPeriodDefinitionsPeriodDestinyTalentNodeCategory {
            identifier: None,
            is_lore_driven: None,
            display_properties: None,
            node_hashes: None,
        }
    }
}


