/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyObjectiveDisplayProperties {
    /// The activity associated with this objective in the context of this item, if any.
    #[serde(rename = "activityHash", skip_serializing_if = "Option::is_none")]
    pub activity_hash: Option<i32>,
    /// If true, the game shows this objective on item preview screens.
    #[serde(rename = "displayOnItemPreviewScreen", skip_serializing_if = "Option::is_none")]
    pub display_on_item_preview_screen: Option<bool>,
}

impl DestinyPeriodDefinitionsPeriodDestinyObjectiveDisplayProperties {
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyObjectiveDisplayProperties {
        DestinyPeriodDefinitionsPeriodDestinyObjectiveDisplayProperties {
            activity_hash: None,
            display_on_item_preview_screen: None,
        }
    }
}


