/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDestinyTalentNodeNodeStatsBlock : This property has some history. A talent grid can provide stats on both the item it's related to and the character equipping the item. This returns data about those stat bonuses.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDestinyTalentNodeNodeStatsBlock {
    /// The stat benefits conferred when this talent node is activated for the current Step that is active on the node.
    #[serde(rename = "currentStepStats", skip_serializing_if = "Option::is_none")]
    pub current_step_stats: Option<Vec<crate::models::DestinyPeriodDestinyStat>>,
    /// This is a holdover from the old days of Destiny 1, when a node could be activated multiple times, conferring multiple steps worth of benefits: you would use this property to show what activating the \"next\" step on the node would provide vs. what the current step is providing. While Nodes are currently not being used this way, the underlying system for this functionality still exists. I hesitate to remove this property while the ability for designers to make such a talent grid still exists. Whether you want to show it is up to you.
    #[serde(rename = "nextStepStats", skip_serializing_if = "Option::is_none")]
    pub next_step_stats: Option<Vec<crate::models::DestinyPeriodDestinyStat>>,
}

impl DestinyDestinyTalentNodeNodeStatsBlock {
    /// This property has some history. A talent grid can provide stats on both the item it's related to and the character equipping the item. This returns data about those stat bonuses.
    pub fn new() -> DestinyDestinyTalentNodeNodeStatsBlock {
        DestinyDestinyTalentNodeNodeStatsBlock {
            current_step_stats: None,
            next_step_stats: None,
        }
    }
}


