/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphDisplayObjectiveDefinition : When a Graph needs to show active Objectives, this defines those objectives as well as an identifier.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphDisplayObjectiveDefinition {
    /// $NOTE $amola 2017-01-19 This field is apparently something that CUI uses to manually wire up objectives to display info. I am unsure how it works.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The objective being shown on the map.
    #[serde(rename = "objectiveHash", skip_serializing_if = "Option::is_none")]
    pub objective_hash: Option<i32>,
}

impl DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphDisplayObjectiveDefinition {
    /// When a Graph needs to show active Objectives, this defines those objectives as well as an identifier.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphDisplayObjectiveDefinition {
        DestinyPeriodDefinitionsPeriodDirectorPeriodDestinyActivityGraphDisplayObjectiveDefinition {
            id: None,
            objective_hash: None,
        }
    }
}


