/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodResponsesPeriodInventoryChangedResponse : A response containing all of the components for all requested vendors.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodResponsesPeriodInventoryChangedResponse {
    /// Items that appeared in the inventory possibly as a result of an action.
    #[serde(rename = "addedInventoryItems", skip_serializing_if = "Option::is_none")]
    pub added_inventory_items: Option<Vec<crate::models::DestinyPeriodEntitiesPeriodItemsPeriodDestinyItemComponent>>,
    /// Items that disappeared from the inventory possibly as a result of an action.
    #[serde(rename = "removedInventoryItems", skip_serializing_if = "Option::is_none")]
    pub removed_inventory_items: Option<Vec<crate::models::DestinyPeriodEntitiesPeriodItemsPeriodDestinyItemComponent>>,
}

impl DestinyPeriodResponsesPeriodInventoryChangedResponse {
    /// A response containing all of the components for all requested vendors.
    pub fn new() -> DestinyPeriodResponsesPeriodInventoryChangedResponse {
        DestinyPeriodResponsesPeriodInventoryChangedResponse {
            added_inventory_items: None,
            removed_inventory_items: None,
        }
    }
}


