/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyVendorRequirementDisplayEntryDefinition : The localized properties of the requirementsDisplay, allowing information about the requirement or item being featured to be seen.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyVendorRequirementDisplayEntryDefinition {
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl DestinyPeriodDefinitionsPeriodDestinyVendorRequirementDisplayEntryDefinition {
    /// The localized properties of the requirementsDisplay, allowing information about the requirement or item being featured to be seen.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyVendorRequirementDisplayEntryDefinition {
        DestinyPeriodDefinitionsPeriodDestinyVendorRequirementDisplayEntryDefinition {
            icon: None,
            name: None,
            source: None,
            r#type: None,
        }
    }
}


