/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodComponentsPeriodMetricsPeriodDestinyMetricComponent {
    #[serde(rename = "invisible", skip_serializing_if = "Option::is_none")]
    pub invisible: Option<bool>,
    #[serde(rename = "objectiveProgress", skip_serializing_if = "Option::is_none")]
    pub objective_progress: Option<Box<crate::models::DestinyPeriodQuestsPeriodDestinyObjectiveProgress>>,
}

impl DestinyPeriodComponentsPeriodMetricsPeriodDestinyMetricComponent {
    pub fn new() -> DestinyPeriodComponentsPeriodMetricsPeriodDestinyMetricComponent {
        DestinyPeriodComponentsPeriodMetricsPeriodDestinyMetricComponent {
            invisible: None,
            objective_progress: None,
        }
    }
}


