/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsActionRequest {
    /// Action token provided by the AwaGetActionToken API call.
    #[serde(rename = "actionToken", skip_serializing_if = "Option::is_none")]
    pub action_token: Option<String>,
    /// The instance ID of the item having a plug inserted. Only instanced items can have sockets.
    #[serde(rename = "itemInstanceId", skip_serializing_if = "Option::is_none")]
    pub item_instance_id: Option<i64>,
    #[serde(rename = "plug", skip_serializing_if = "Option::is_none")]
    pub plug: Option<Box<crate::models::DestinyRequestsActionsDestinyInsertPlugsActionRequestPlug>>,
    #[serde(rename = "characterId", skip_serializing_if = "Option::is_none")]
    pub character_id: Option<i64>,
    #[serde(rename = "membershipType", skip_serializing_if = "Option::is_none")]
    pub membership_type: Option<i32>,
}

impl DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsActionRequest {
    pub fn new() -> DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsActionRequest {
        DestinyPeriodRequestsPeriodActionsPeriodDestinyInsertPlugsActionRequest {
            action_token: None,
            item_instance_id: None,
            plug: None,
            character_id: None,
            membership_type: None,
        }
    }
}


