/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodAnimationsPeriodDestinyAnimationReference {
    #[serde(rename = "animName", skip_serializing_if = "Option::is_none")]
    pub anim_name: Option<String>,
    #[serde(rename = "animIdentifier", skip_serializing_if = "Option::is_none")]
    pub anim_identifier: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl DestinyPeriodDefinitionsPeriodAnimationsPeriodDestinyAnimationReference {
    pub fn new() -> DestinyPeriodDefinitionsPeriodAnimationsPeriodDestinyAnimationReference {
        DestinyPeriodDefinitionsPeriodAnimationsPeriodDestinyAnimationReference {
            anim_name: None,
            anim_identifier: None,
            path: None,
        }
    }
}


