/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyInventoryItemDefinitionSockets : If this item has any Sockets, this will be non-null and the individual sockets on the item will be defined herein.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyInventoryItemDefinitionSockets {
    /// This was supposed to be a string that would give per-item details about sockets. In practice, it turns out that all this ever has is the localized word \"details\". ... that's lame, but perhaps it will become something cool in the future.
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Each non-intrinsic (or mutable) socket on an item is defined here. Check inside for more info.
    #[serde(rename = "socketEntries", skip_serializing_if = "Option::is_none")]
    pub socket_entries: Option<Vec<crate::models::DestinyPeriodDefinitionsPeriodDestinyItemSocketEntryDefinition>>,
    /// Each intrinsic (or immutable/permanent) socket on an item is defined here, along with the plug that is permanently affixed to the socket.
    #[serde(rename = "intrinsicSockets", skip_serializing_if = "Option::is_none")]
    pub intrinsic_sockets: Option<Vec<crate::models::DestinyPeriodDefinitionsPeriodDestinyItemIntrinsicSocketEntryDefinition>>,
    /// A convenience property, that refers to the sockets in the \"sockets\" property, pre-grouped by category and ordered in the manner that they should be grouped in the UI. You could form this yourself with the existing data, but why would you want to? Enjoy life man.
    #[serde(rename = "socketCategories", skip_serializing_if = "Option::is_none")]
    pub socket_categories: Option<Vec<crate::models::DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition>>,
}

impl DestinyDefinitionsDestinyInventoryItemDefinitionSockets {
    /// If this item has any Sockets, this will be non-null and the individual sockets on the item will be defined herein.
    pub fn new() -> DestinyDefinitionsDestinyInventoryItemDefinitionSockets {
        DestinyDefinitionsDestinyInventoryItemDefinitionSockets {
            detail: None,
            socket_entries: None,
            intrinsic_sockets: None,
            socket_categories: None,
        }
    }
}


