/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyEntitiesCharactersDestinyCharacterComponentEmblemColor : A shortcut for getting the background color of the user's currently equipped emblem without having to do a DestinyInventoryItemDefinition lookup.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyEntitiesCharactersDestinyCharacterComponentEmblemColor {
    #[serde(rename = "red", skip_serializing_if = "Option::is_none")]
    pub red: Option<String>,
    #[serde(rename = "green", skip_serializing_if = "Option::is_none")]
    pub green: Option<String>,
    #[serde(rename = "blue", skip_serializing_if = "Option::is_none")]
    pub blue: Option<String>,
    #[serde(rename = "alpha", skip_serializing_if = "Option::is_none")]
    pub alpha: Option<String>,
}

impl DestinyEntitiesCharactersDestinyCharacterComponentEmblemColor {
    /// A shortcut for getting the background color of the user's currently equipped emblem without having to do a DestinyInventoryItemDefinition lookup.
    pub fn new() -> DestinyEntitiesCharactersDestinyCharacterComponentEmblemColor {
        DestinyEntitiesCharactersDestinyCharacterComponentEmblemColor {
            red: None,
            green: None,
            blue: None,
            alpha: None,
        }
    }
}


