/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodAdvancedPeriodAwaInitializeResponse {
    /// ID used to get the token. Present this ID to the user as it will identify this specific request on their device.
    #[serde(rename = "correlationId", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// True if the PUSH message will only be sent to the device that made this request.
    #[serde(rename = "sentToSelf", skip_serializing_if = "Option::is_none")]
    pub sent_to_self: Option<bool>,
}

impl DestinyPeriodAdvancedPeriodAwaInitializeResponse {
    pub fn new() -> DestinyPeriodAdvancedPeriodAwaInitializeResponse {
        DestinyPeriodAdvancedPeriodAwaInitializeResponse {
            correlation_id: None,
            sent_to_self: None,
        }
    }
}


