/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyDefinitionsDestinyInventoryItemDefinitionSack : If this item is a \"reward sack\" that can be opened to provide other items, this will be non-null and the properties of the sack contained herein.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyDefinitionsDestinyInventoryItemDefinitionSack {
    /// A description of what will happen when you open the sack. As far as I can tell, this is blank currently. Unknown whether it will eventually be populated with useful info.
    #[serde(rename = "detailAction", skip_serializing_if = "Option::is_none")]
    pub detail_action: Option<String>,
    /// The localized name of the action being performed when you open the sack.
    #[serde(rename = "openAction", skip_serializing_if = "Option::is_none")]
    pub open_action: Option<String>,
    #[serde(rename = "selectItemCount", skip_serializing_if = "Option::is_none")]
    pub select_item_count: Option<i32>,
    #[serde(rename = "vendorSackType", skip_serializing_if = "Option::is_none")]
    pub vendor_sack_type: Option<String>,
    #[serde(rename = "openOnAcquire", skip_serializing_if = "Option::is_none")]
    pub open_on_acquire: Option<bool>,
}

impl DestinyDefinitionsDestinyInventoryItemDefinitionSack {
    /// If this item is a \"reward sack\" that can be opened to provide other items, this will be non-null and the properties of the sack contained herein.
    pub fn new() -> DestinyDefinitionsDestinyInventoryItemDefinitionSack {
        DestinyDefinitionsDestinyInventoryItemDefinitionSack {
            detail_action: None,
            open_action: None,
            select_item_count: None,
            vendor_sack_type: None,
            open_on_acquire: None,
        }
    }
}


