/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition : Sockets are grouped into categories in the UI. These define which category and which sockets are under that category.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition {
    /// The hash for the Socket Category: a quick way to go get the header display information for the category. Use it to look up DestinySocketCategoryDefinition info.
    #[serde(rename = "socketCategoryHash", skip_serializing_if = "Option::is_none")]
    pub socket_category_hash: Option<i32>,
    /// Use these indexes to look up the sockets in the \"sockets.socketEntries\" property on the item definition. These are the indexes under the category, in game-rendered order.
    #[serde(rename = "socketIndexes", skip_serializing_if = "Option::is_none")]
    pub socket_indexes: Option<Vec<i32>>,
}

impl DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition {
    /// Sockets are grouped into categories in the UI. These define which category and which sockets are under that category.
    pub fn new() -> DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition {
        DestinyPeriodDefinitionsPeriodDestinyItemSocketCategoryDefinition {
            socket_category_hash: None,
            socket_indexes: None,
        }
    }
}


