/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ForumPeriodPollResponse {
    #[serde(rename = "topicId", skip_serializing_if = "Option::is_none")]
    pub topic_id: Option<i64>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<crate::models::ForumPeriodPollResult>>,
    #[serde(rename = "totalVotes", skip_serializing_if = "Option::is_none")]
    pub total_votes: Option<i32>,
}

impl ForumPeriodPollResponse {
    pub fn new() -> ForumPeriodPollResponse {
        ForumPeriodPollResponse {
            topic_id: None,
            results: None,
            total_votes: None,
        }
    }
}


