/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ForumPeriodForumRecruitmentDetail {
    #[serde(rename = "topicId", skip_serializing_if = "Option::is_none")]
    pub topic_id: Option<i64>,
    #[serde(rename = "microphoneRequired", skip_serializing_if = "Option::is_none")]
    pub microphone_required: Option<bool>,
    #[serde(rename = "intensity", skip_serializing_if = "Option::is_none")]
    pub intensity: Option<i32>,
    #[serde(rename = "tone", skip_serializing_if = "Option::is_none")]
    pub tone: Option<i32>,
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    #[serde(rename = "conversationId", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<i64>,
    #[serde(rename = "playerSlotsTotal", skip_serializing_if = "Option::is_none")]
    pub player_slots_total: Option<i32>,
    #[serde(rename = "playerSlotsRemaining", skip_serializing_if = "Option::is_none")]
    pub player_slots_remaining: Option<i32>,
    #[serde(rename = "Fireteam", skip_serializing_if = "Option::is_none")]
    pub fireteam: Option<Vec<crate::models::UserPeriodGeneralUser>>,
    #[serde(rename = "kickedPlayerIds", skip_serializing_if = "Option::is_none")]
    pub kicked_player_ids: Option<Vec<i64>>,
}

impl ForumPeriodForumRecruitmentDetail {
    pub fn new() -> ForumPeriodForumRecruitmentDetail {
        ForumPeriodForumRecruitmentDetail {
            topic_id: None,
            microphone_required: None,
            intensity: None,
            tone: None,
            approved: None,
            conversation_id: None,
            player_slots_total: None,
            player_slots_remaining: None,
            fireteam: None,
            kicked_player_ids: None,
        }
    }
}


