/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupsV2PeriodGroupNameSearchRequest {
    #[serde(rename = "groupName", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "groupType", skip_serializing_if = "Option::is_none")]
    pub group_type: Option<i32>,
}

impl GroupsV2PeriodGroupNameSearchRequest {
    pub fn new() -> GroupsV2PeriodGroupNameSearchRequest {
        GroupsV2PeriodGroupNameSearchRequest {
            group_name: None,
            group_type: None,
        }
    }
}


