/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupsV2PeriodGroupOptionalConversationAddRequest {
    #[serde(rename = "chatName", skip_serializing_if = "Option::is_none")]
    pub chat_name: Option<String>,
    #[serde(rename = "chatSecurity", skip_serializing_if = "Option::is_none")]
    pub chat_security: Option<i32>,
}

impl GroupsV2PeriodGroupOptionalConversationAddRequest {
    pub fn new() -> GroupsV2PeriodGroupOptionalConversationAddRequest {
        GroupsV2PeriodGroupOptionalConversationAddRequest {
            chat_name: None,
            chat_security: None,
        }
    }
}


