/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupsV2PeriodClanBanner {
    #[serde(rename = "decalId", skip_serializing_if = "Option::is_none")]
    pub decal_id: Option<i32>,
    #[serde(rename = "decalColorId", skip_serializing_if = "Option::is_none")]
    pub decal_color_id: Option<i32>,
    #[serde(rename = "decalBackgroundColorId", skip_serializing_if = "Option::is_none")]
    pub decal_background_color_id: Option<i32>,
    #[serde(rename = "gonfalonId", skip_serializing_if = "Option::is_none")]
    pub gonfalon_id: Option<i32>,
    #[serde(rename = "gonfalonColorId", skip_serializing_if = "Option::is_none")]
    pub gonfalon_color_id: Option<i32>,
    #[serde(rename = "gonfalonDetailId", skip_serializing_if = "Option::is_none")]
    pub gonfalon_detail_id: Option<i32>,
    #[serde(rename = "gonfalonDetailColorId", skip_serializing_if = "Option::is_none")]
    pub gonfalon_detail_color_id: Option<i32>,
}

impl GroupsV2PeriodClanBanner {
    pub fn new() -> GroupsV2PeriodClanBanner {
        GroupsV2PeriodClanBanner {
            decal_id: None,
            decal_color_id: None,
            decal_background_color_id: None,
            gonfalon_id: None,
            gonfalon_color_id: None,
            gonfalon_detail_id: None,
            gonfalon_detail_color_id: None,
        }
    }
}


