/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// GroupsV2PeriodGroupQuery : NOTE: GroupQuery, as of Destiny 2, has essentially two totally different and incompatible \"modes\".  If you are querying for a group, you can pass any of the properties below.  If you are querying for a Clan, you MUST NOT pass any of the following properties (they must be null or undefined in your request, not just empty string/default values):  - groupMemberCountFilter - localeFilter - tagText  If you pass these, you will get a useless InvalidParameters error.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupsV2PeriodGroupQuery {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "groupType", skip_serializing_if = "Option::is_none")]
    pub group_type: Option<i32>,
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<i32>,
    #[serde(rename = "sortBy", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<i32>,
    #[serde(rename = "groupMemberCountFilter", skip_serializing_if = "Option::is_none")]
    pub group_member_count_filter: Option<GroupMemberCountFilter>,
    #[serde(rename = "localeFilter", skip_serializing_if = "Option::is_none")]
    pub locale_filter: Option<String>,
    #[serde(rename = "tagText", skip_serializing_if = "Option::is_none")]
    pub tag_text: Option<String>,
    #[serde(rename = "itemsPerPage", skip_serializing_if = "Option::is_none")]
    pub items_per_page: Option<i32>,
    #[serde(rename = "currentPage", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "requestContinuationToken", skip_serializing_if = "Option::is_none")]
    pub request_continuation_token: Option<String>,
}

impl GroupsV2PeriodGroupQuery {
    /// NOTE: GroupQuery, as of Destiny 2, has essentially two totally different and incompatible \"modes\".  If you are querying for a group, you can pass any of the properties below.  If you are querying for a Clan, you MUST NOT pass any of the following properties (they must be null or undefined in your request, not just empty string/default values):  - groupMemberCountFilter - localeFilter - tagText  If you pass these, you will get a useless InvalidParameters error.
    pub fn new() -> GroupsV2PeriodGroupQuery {
        GroupsV2PeriodGroupQuery {
            name: None,
            group_type: None,
            creation_date: None,
            sort_by: None,
            group_member_count_filter: None,
            locale_filter: None,
            tag_text: None,
            items_per_page: None,
            current_page: None,
            request_continuation_token: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupMemberCountFilter {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for GroupMemberCountFilter {
    fn default() -> GroupMemberCountFilter {
        Self::Variant0
    }
}

