/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IgnoresPeriodIgnoreResponse {
    #[serde(rename = "isIgnored", skip_serializing_if = "Option::is_none")]
    pub is_ignored: Option<bool>,
    #[serde(rename = "ignoreFlags", skip_serializing_if = "Option::is_none")]
    pub ignore_flags: Option<i32>,
}

impl IgnoresPeriodIgnoreResponse {
    pub fn new() -> IgnoresPeriodIgnoreResponse {
        IgnoresPeriodIgnoreResponse {
            is_ignored: None,
            ignore_flags: None,
        }
    }
}


