/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueriesPeriodPagedQuery {
    #[serde(rename = "itemsPerPage", skip_serializing_if = "Option::is_none")]
    pub items_per_page: Option<i32>,
    #[serde(rename = "currentPage", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "requestContinuationToken", skip_serializing_if = "Option::is_none")]
    pub request_continuation_token: Option<String>,
}

impl QueriesPeriodPagedQuery {
    pub fn new() -> QueriesPeriodPagedQuery {
        QueriesPeriodPagedQuery {
            items_per_page: None,
            current_page: None,
            request_continuation_token: None,
        }
    }
}


