/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SocialPeriodFriendsPeriodBungieFriend {
    #[serde(rename = "lastSeenAsMembershipId", skip_serializing_if = "Option::is_none")]
    pub last_seen_as_membership_id: Option<i64>,
    #[serde(rename = "lastSeenAsBungieMembershipType", skip_serializing_if = "Option::is_none")]
    pub last_seen_as_bungie_membership_type: Option<i32>,
    #[serde(rename = "bungieGlobalDisplayName", skip_serializing_if = "Option::is_none")]
    pub bungie_global_display_name: Option<String>,
    #[serde(rename = "bungieGlobalDisplayNameCode", skip_serializing_if = "Option::is_none")]
    pub bungie_global_display_name_code: Option<i32>,
    #[serde(rename = "onlineStatus", skip_serializing_if = "Option::is_none")]
    pub online_status: Option<i32>,
    #[serde(rename = "onlineTitle", skip_serializing_if = "Option::is_none")]
    pub online_title: Option<i32>,
    #[serde(rename = "relationship", skip_serializing_if = "Option::is_none")]
    pub relationship: Option<i32>,
    #[serde(rename = "bungieNetUser", skip_serializing_if = "Option::is_none")]
    pub bungie_net_user: Option<Box<crate::models::UserPeriodGeneralUser>>,
}

impl SocialPeriodFriendsPeriodBungieFriend {
    pub fn new() -> SocialPeriodFriendsPeriodBungieFriend {
        SocialPeriodFriendsPeriodBungieFriend {
            last_seen_as_membership_id: None,
            last_seen_as_bungie_membership_type: None,
            bungie_global_display_name: None,
            bungie_global_display_name_code: None,
            online_status: None,
            online_title: None,
            relationship: None,
            bungie_net_user: None,
        }
    }
}


