/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokensPeriodPartnerRewardHistoryResponse {
    #[serde(rename = "PartnerOffers", skip_serializing_if = "Option::is_none")]
    pub partner_offers: Option<Vec<crate::models::TokensPeriodPartnerOfferSkuHistoryResponse>>,
    #[serde(rename = "TwitchDrops", skip_serializing_if = "Option::is_none")]
    pub twitch_drops: Option<Vec<crate::models::TokensPeriodTwitchDropHistoryResponse>>,
}

impl TokensPeriodPartnerRewardHistoryResponse {
    pub fn new() -> TokensPeriodPartnerRewardHistoryResponse {
        TokensPeriodPartnerRewardHistoryResponse {
            partner_offers: None,
            twitch_drops: None,
        }
    }
}


