/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokensPeriodUserRewardAvailabilityModel {
    #[serde(rename = "AvailabilityModel", skip_serializing_if = "Option::is_none")]
    pub availability_model: Option<Box<crate::models::TokensPeriodRewardAvailabilityModel>>,
    #[serde(rename = "IsAvailableForUser", skip_serializing_if = "Option::is_none")]
    pub is_available_for_user: Option<bool>,
    #[serde(rename = "IsUnlockedForUser", skip_serializing_if = "Option::is_none")]
    pub is_unlocked_for_user: Option<bool>,
}

impl TokensPeriodUserRewardAvailabilityModel {
    pub fn new() -> TokensPeriodUserRewardAvailabilityModel {
        TokensPeriodUserRewardAvailabilityModel {
            availability_model: None,
            is_available_for_user: None,
            is_unlocked_for_user: None,
        }
    }
}


