/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// UserPeriodEMailSettingLocalization : Localized text relevant to a given EMail setting in a given localization.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserPeriodEMailSettingLocalization {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl UserPeriodEMailSettingLocalization {
    /// Localized text relevant to a given EMail setting in a given localization.
    pub fn new() -> UserPeriodEMailSettingLocalization {
        UserPeriodEMailSettingLocalization {
            title: None,
            description: None,
        }
    }
}


