/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserPeriodUserToUserContext {
    #[serde(rename = "isFollowing", skip_serializing_if = "Option::is_none")]
    pub is_following: Option<bool>,
    #[serde(rename = "ignoreStatus", skip_serializing_if = "Option::is_none")]
    pub ignore_status: Option<Box<crate::models::IgnoresPeriodIgnoreResponse>>,
    #[serde(rename = "globalIgnoreEndDate", skip_serializing_if = "Option::is_none")]
    pub global_ignore_end_date: Option<String>,
}

impl UserPeriodUserToUserContext {
    pub fn new() -> UserPeriodUserToUserContext {
        UserPeriodUserToUserContext {
            is_following: None,
            ignore_status: None,
            global_ignore_end_date: None,
        }
    }
}


