/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserPeriodHardLinkedUserMembership {
    #[serde(rename = "membershipType", skip_serializing_if = "Option::is_none")]
    pub membership_type: Option<i32>,
    #[serde(rename = "membershipId", skip_serializing_if = "Option::is_none")]
    pub membership_id: Option<i64>,
    #[serde(rename = "CrossSaveOverriddenType", skip_serializing_if = "Option::is_none")]
    pub cross_save_overridden_type: Option<i32>,
    #[serde(rename = "CrossSaveOverriddenMembershipId", skip_serializing_if = "Option::is_none")]
    pub cross_save_overridden_membership_id: Option<i64>,
}

impl UserPeriodHardLinkedUserMembership {
    pub fn new() -> UserPeriodHardLinkedUserMembership {
        UserPeriodHardLinkedUserMembership {
            membership_type: None,
            membership_id: None,
            cross_save_overridden_type: None,
            cross_save_overridden_membership_id: None,
        }
    }
}


