/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 */

/// UserPeriodEmailSubscriptionDefinition : Defines a single subscription: permission to send emails for a specific, focused subject (generally timeboxed, such as for a specific release of a product or feature).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserPeriodEmailSubscriptionDefinition {
    /// The unique identifier for this subscription.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A dictionary of localized text for the EMail Opt-in setting, keyed by the locale.
    #[serde(rename = "localization", skip_serializing_if = "Option::is_none")]
    pub localization: Option<::std::collections::HashMap<String, crate::models::UserPeriodEMailSettingSubscriptionLocalization>>,
    /// The bitflag value for this subscription. Should be a unique power of two value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
}

impl UserPeriodEmailSubscriptionDefinition {
    /// Defines a single subscription: permission to send emails for a specific, focused subject (generally timeboxed, such as for a specific release of a product or feature).
    pub fn new() -> UserPeriodEmailSubscriptionDefinition {
        UserPeriodEmailSubscriptionDefinition {
            name: None,
            localization: None,
            value: None,
        }
    }
}


